# Generated by Django 5.1.1 on 2024-09-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='catgory',
            new_name='category',
        ),
    ]
